const express = require ("express");
const router = express.Router();
module.exports = router;
require("./paramedicRoute");
require("./Register/patientRoute");
require("./Register/paramedicRoute");
require("./Register/doctorRoute");
require("./Register/ambulanceRoute");
require("./Register/registerRoute");
require("./loginUtilities");
require("./logoutUtilities");
require("./incident");
require("./media");